# Copyright (c) 2023-2025 Boston Dynamics AI Institute LLC. All rights reserved.

base:
  stand:
    joint_positions:
      # fl_hx: 0.12
      # fl_hy: 0.72
      # fl_kn: -1.45
      # fr_hx: -0.12
      # fr_hy: 0.72
      # fr_kn: -1.45
      # hl_hx: 0.12
      # hl_hy: 0.72
      # hl_kn: -1.45
      # hr_hx: -0.12
      # hr_hy: 0.72
      # hr_kn: -1.45
      front_left_hip_x: 0.12
      front_left_hip_y: 0.72
      front_left_knee: -1.45
      front_right_hip_x: -0.12
      front_right_hip_y: 0.72
      front_right_knee: -1.45
      rear_left_hip_x: 0.12
      rear_left_hip_y: 0.72
      rear_left_knee: -1.45
      rear_right_hip_x: -0.12
      rear_right_hip_y: 0.72
      rear_right_knee: -1.45
    translation: [0, 0, 0.525]
  sit:
    joint_positions:
      front_left_hip_x: 0.48
      front_left_hip_y: 1.26
      front_left_knee: -2.7929
      front_right_hip_x: -0.48
      front_right_hip_y: 1.26
      front_right_knee: -2.7929
      rear_left_hip_x: 0.48
      rear_left_hip_y: 1.26
      rear_left_knee: -2.7929
      rear_right_hip_x: -0.48
      rear_right_hip_y: 1.26
      rear_right_knee: -2.7929
    translation: [0, 0, 0.104]
arm:
  stow:
    joint_positions:
      arm_sh0: 0.0
      arm_sh1: -3.12
      arm_el0: 3.13
      arm_el1: 1.57
      arm_wr0: -0.0
      arm_wr1: -1.57
  unstow:
    joint_positions:
      arm_sh0: 0.0
      arm_sh1: -0.9
      arm_el0: 1.8
      arm_el1: 0.0
      arm_wr0: -0.9
      arm_wr1: -0.0
gripper:
  open:
    joint_positions:
      arm_f1x: -1.54
  closed:
    joint_positions:
      arm_f1x: -0.054
