# Copyright (c) 2023-2025 Boston Dynamics AI Institute LLC. All rights reserved.

base:
  stand:
    joint_positions:
      fl_hx: 0.12
      fl_hy: 0.72
      fl_kn: -1.45
      fr_hx: -0.12
      fr_hy: 0.72
      fr_kn: -1.45
      hl_hx: 0.12
      hl_hy: 0.72
      hl_kn: -1.45
      hr_hx: -0.12
      hr_hy: 0.72
      hr_kn: -1.45
    translation: [0, 0, 0.525]
  sit:
    joint_positions:
      fl_hx: 0.48
      fl_hy: 1.26
      fl_kn: -2.7929
      fr_hx: -0.48
      fr_hy: 1.26
      fr_kn: -2.7929
      hl_hx: 0.48
      hl_hy: 1.26
      hl_kn: -2.7929
      hr_hx: -0.48
      hr_hy: 1.26
      hr_kn: -2.7929
    translation: [0, 0, 0.104]
arm:
  stow:
    joint_positions:
      arm0_sh0: 0.0
      arm0_sh1: -3.12
      arm0_el0: 3.13
      arm0_el1: 1.57
      arm0_wr0: -0.0
      arm0_wr1: -1.57
  unstow:
    joint_positions:
      arm0_sh0: 0.0
      arm0_sh1: -0.9
      arm0_el0: 1.8
      arm0_el1: 0.0
      arm0_wr0: -0.9
      arm0_wr1: -0.0
gripper:
  open:
    joint_positions:
      arm0_f1x: -1.54
  closed:
    joint_positions:
      arm0_f1x: -0.054
